apiVersion: v1
kind: Service
metadata:
  name: don-king-test1
  namespace: frontend
  labels:
    app: don-king-test1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: don-king-test1
